### ISSUE TITLE
section5.5中结构约束信息

### ISSUE THREAD

**Issue by mencyhuang** [ZhengyuZhao/PerC-Adversarial#1]
请问这部分代码有公布么？暂时没有找到

**Comment by ZhengyuZhao** [comment]
> 请问这部分代码有公布么？暂时没有
不好意思，这部分是主算法的简单扩展，并只在figure 5进行了定性展示，所以并没有上传代码。不过section 5.5中的文字描述已经包含了所有细节：this vector is obtained by calculating the standard deviation of the pixel values in each 3 × 3 square per channel. The components with top 5% highest values in the map are clipped for stability and the map is normalized into the range [0,1] before use.

**Comment by ZhengyuZhao** [comment]
> 请问这部分代码有公布么？暂时没有找到

不好意思，这部分是主算法的简单扩展，并只在figure 5进行了定性展示，所以并没有上传代码。不过section 5.5中的文字描述已经包含了所有细节：this vector is obtained by calculating the standard deviation of the pixel values in each 3 × 3 square per channel. The components with top 5% highest values in the map are clipped for stability and the map is normalized into the range [0,1] before use.

**Comment by mencyhuang** [comment]
> > 请问这部分代码有公布么？暂时没有找到
> 
> 不好意思，这部分是主算法的简单扩展，并只在figure 5进行了定性展示，所以并没有上传代码。不过section 5.5中的文字描述已经包含了所有细节：this vector is obtained by calculating the standard deviation of the pixel values in each 3 × 3 square per channel. The components with top 5% highest values in the map are clipped for stability and the map is normalized into the range [0,1] before use.

你们参考引文【11】里的用法，是自己实现的pytorch版本么？不太熟悉TF，如果有torch版本的就太好了！

**Comment by ZhengyuZhao** [comment]
> > > 请问这部分代码有公布么？暂时没有找到
> > 
> > 
> > 不好意思，这部分是主算法的简单扩展，并只在figure 5进行了定性展示，所以并没有上传代码。不过section 5.5中的文字描述已经包含了所有细节：this vector is obtained by calculating the standard deviation of the pixel values in each 3 × 3 square per channel. The components with top 5% highest values in the map are clipped for stability and the map is normalized into the range [0,1] before use.
> 
> 你们参考引文【11】里的用法，是自己实现的pytorch版本么？不太熟悉TF，如果有torch版本的就太好了！

引文里的具体实现用的什么语言我不太清楚，pytorch应该是直接用torch.std就可以算standard deviation。其他的都是很简单的操作了
