### ISSUE TITLE
您好，有问题想问您

### ISSUE THREAD

**Issue by K1-aus** [ZhengyuZhao/PerC-Adversarial#11]
您好，我是中南大学的一名本科生，无意间在csdn上看到了您的这个方法。因为自己是对抗样本领域的门外汉，虽然将您的源码成功运行，但结果是“进程已结束,退出代码0”。
所以想问您运行结果是正常的吗？有成功生成对抗样本了吗？
希望能得到您的答复，谢谢。

**Comment by ZhengyuZhao** [comment]
> 您好，我是中南大学的一名本科生，无意间在csdn上看到了您的这个方法。因为自己是对抗样本领域的门外汉，虽然将您的源码成功运行，但结果是“进程已结束,退出代码0”。 所以想问您运行结果是正常的吗？有成功生成对抗样本了吗？ 希望能得到您的答复，谢谢。

您好，感谢您对我们工作的兴趣。我这里是可以正常运行代码得到对抗样本的。你可以提供更多的代码细节嘛（比如截图）？

**Comment by K1-aus** [comment]
我在pycharm您的[perc_al.py]文件运行之后，结果返回“进程已结束,退出代码0”。请问得到的对抗样本放在哪里了呢？

**Comment by ZhengyuZhao** [comment]
perc_al.py不是可以独立运行的文件，您需要执行主文件main.ipynb，里面有详细的注释，并且会调用到perc_al.py里面定义的函数

**Comment by K1-aus** [comment]
您好 我这边运行了主文件
第一次运行结果报错提示“FileNotFoundError: [Errno 2] No such file or directory: 'images.csv'”，我尝试着将dataset中的images.csv放到跟主文件同目录下进行第二次运行
第二次运行结果报错提示“AssertionError: Torch not compiled with CUDA enabled”，请问这是什么情况呢？
我的运行环境是pycharm（py3.10），笔记本电脑（R7-4800H RTX2060）

**Comment by ZhengyuZhao** [comment]
> 
这个看起来是你安装的pytorch和CUDA版本匹配的问题，您可以上网搜一下具体的解决方案

**Comment by ZhengyuZhao** [comment]
> 您好 我这边运行了主文件 第一次运行结果报错提示“FileNotFoundError: [Errno 2] No such file or directory: 'images.csv'”，我尝试着将dataset中的images.csv放到跟主文件同目录下进行第二次运行 第二次运行结果报错提示“AssertionError: Torch not compiled with CUDA enabled”，请问这是什么情况呢？ 我的运行环境是pycharm（py3.10），笔记本电脑（R7-4800H RTX2060）

这个看起来是您安装的pytorch和cuda版本匹配的问题，可以网上搜一下具体的解决方案。我也不是太清楚

**Comment by K1-aus** [comment]
好的 谢谢您
