### ISSUE TITLE
关于Perceptual Color distance Alternating Loss问题

### ISSUE THREAD

**Issue by MZener** [ZhengyuZhao/PerC-Adversarial#5]
您好，我在做关于图像增强方面的工作（颜色，亮度），请问您提出来的这个loss可以用来做类似任务计算损失，比较两张图片的差异性吗，我看到的目前有比较两张图像差异性的有psnr，ssim，lpips，您有做过该方面的对比吗，多谢

**Comment by ZhengyuZhao** [comment]
> 您好，我在做关于图像增强方面的工作（颜色，亮度），请问您提出来的这个loss可以用来做类似任务计算损失，比较两张图片的差异性吗，我看到的目前有比较两张图像差异性的有psnr，ssim，lpips，您有做过该方面的对比吗，多谢

没错，这篇论文里面用到的CIEDE2000 metric就是用来比较两张图片差异性的，相关的结果是比如Table 1里面的C2. 相对于传统的psnr和ssim，CIEDE2000 额外考虑了人眼对颜色感知的差异性。

**Comment by ZhengyuZhao** [comment]
solved
