### ISSUE TITLE
figure1

### ISSUE THREAD

**Issue by Kitzzaaa** [ZhengyuZhao/PerC-Adversarial#7]
你好！我想知道关于图1是如何从原图上截取一块并放大的，可以发我一份代码吗?邮箱Zhrong550321308@163.com

**Comment by ZhengyuZhao** [comment]
> 你好！我想知道关于图1是如何从原图上截取一块并放大的，可以发我一份代码吗?邮箱[Zhrong550321308@163.com](mailto:Zhrong550321308@163.com)

你好，图一只是为了展示目的，所以图片截取是通过手动完成的，没有代码

**Comment by Kitzzaaa** [comment]
请问怎么手动完成的？为啥我截取一块放大特别模糊

**Comment by ZhengyuZhao** [comment]
> 请问怎么手动完成的？为啥我截取一块放大特别模糊

图1截取的112x112尺寸的块，你看看你的截取方法是不是有一些默认的压缩操作
